FROM apache/airflow:2.7.1-python3.10

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt

COPY airflow/init-airflow.sh /opt/airflow/init-airflow.sh
USER root
RUN chmod +x /opt/airflow/init-airflow.sh
USER airflow
